services:
  - type: web
    name: n8n
    env: node
    buildCommand: |
      corepack enable
      corepack prepare pnpm@10.2.1 --activate
      pnpm install
      pnpm build || pnpm run build
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
